<a href="https://colab.research.google.com/github/oliviapang/scratchpad/blob/main/Class_2_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/oliviapang/scratchpad
%run ./scratchpad/get_data.py

Cloning into 'scratchpad'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 54 (delta 10), reused 5 (delta 5), pack-reused 35 (from 2)
Receiving objects: 100% (54/54), 1.49 MiB | 10.62 MiB/s, done.
Resolving deltas: 100% (17/17), done.
Downloading course data...
Download complete
Extracting data files...
Data extracted

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import mean_squared_error

In [5]:
df = pd.read_csv('/content/data/CardiacPatientData.csv')
df

,ID,SBP,DBP,HR,RR,BT,SpO2,Age,Gender,GCS,Na,K,Cl,Urea,Ceratinine,Alcoholic,Smoke,FHCD,TriageScore,Outcome
0,1,163,95,90,18,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1
1,1,134,85,85,15,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1
2,1,121,77,80,19,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1
3,1,103,78,70,16,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1
4,1,96,70,59,13,98,98,66,1,15,139.0,4.0,105.0,41.0,91.0,1.0,1.0,0.0,3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5901,112,85,57,142,51,98,92,53,1,15,133.0,4.0,103.0,NaN,NaN,1.0,1.0,0.0,2.0,0
5902,112,101,74,135,29,98,92,53,1,15,133.0,4.0,103.0,NaN,NaN,1.0,1.0,0.0,2.0,0
5903,112,95,64,131,29,98,92,53,1,15,133.0,4.0,103.0,NaN,NaN,1.0,1.0,0.0,2.0,0
5904,112,75,54,121,29,98,92,53,1,15,133.0,4.0,103.0,NaN,NaN,1.0,1.0,0.0,2.0,0
5905,112,73,53,137,29,98,92,53,1,15,133.0,4.0,103.0,NaN,NaN,1.0,1.0,0.0,2.0,0

In [6]:
df.isna().sum()

ID                0
SBP               0
DBP               0
HR                0
RR                0
BT                0
SpO2              0
Age               0
Gender            0
GCS               0
Na             3244
K              3244
Cl             3248
Urea           3320
Ceratinine     3261
Alcoholic      1751
Smoke          1752
FHCD           1621
TriageScore    1903
Outcome           0
dtype: int64

In [7]:
df.columns

Index(['ID', 'SBP', 'DBP', 'HR', 'RR', 'BT', 'SpO2', 'Age', 'Gender', 'GCS',
       'Na', 'K', 'Cl', 'Urea', 'Ceratinine', 'Alcoholic', 'Smoke', 'FHCD',
       'TriageScore', 'Outcome'],
      dtype='object')

In [8]:
vars = ['SBP', 'DBP', 'HR', 'RR', 'BT', 'SpO2', 'Age']
x = df.loc[:, vars]
y = df['Outcome']

In [15]:
expander = PolynomialFeatures(degree=2, include_bias=False)
X_poly = expander.fit_transform(X)
X_names = expander.get_feature_names_out()

model = LinearRegression()

kfold = KFold(n_splits=10, shuffle=True, random_state=100) # Create folds

scores = cross_val_score( # Conduct kfcv:
    model,X_poly,y, # Model and data
    cv=kfold, # Folds
    scoring=mean_squared_error # Loss function
)

mse = -scores
'''
print("Fold scores:", scores)
print("Mean score:", np.mean(scores))
print("Median score:", np.median(scores))
print("Std dev:", np.std(scores))
'''

NameError: name 'X' is not defined